Update ov_fifo_test.ino
Removed 'static' from interrupt funtion declaration because it was causing a compilation error in some Arduino versions:

ov_fifo_test:164: error: ambiguating new declaration of 'void vsyncIntFunc()'

void static __inline__ vsyncIntFunc() {

^

C:\Users\Little\Documents\Arduino\ov_fifo_test\ov_fifo_test.ino:164:19: note: old declaration 'int vsyncIntFunc()'

void static __inline__ vsyncIntFunc() {

^

Using library Wire at version 1.0 in folder: C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire 
exit status 1
ambiguating new declaration of 'void vsyncIntFunc()'